In [11]:
import pandas as pd
from pathlib import Path


inputPath = Path("/Users/saeedfakhouri/Desktop/LaLiga_CIB_Project/data/LaLiga_Stats_CIB.xlsx")

dataExcel = pd.read_excel(inputPath, sheet_name="LaLigaTables", header=None)

cleanRows = []
currentSeason = None

In [12]:
dataExcel.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11
0,Season 2020-21,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Source: https://en.wikipedia.org/wiki/2020–21_...
1,NaN,1,Atlético Madrid,38,26,8,4,67,25,42,86,NaN
2,NaN,2,Real Madrid,38,25,9,4,67,28,39,84,NaN
3,NaN,3,Barcelona,38,24,7,7,85,38,47,79,NaN
4,NaN,4,Sevilla,38,24,5,9,53,33,20,77,NaN
5,NaN,5,Real Sociedad,38,17,11,10,59,38,21,62,NaN
6,NaN,6,Real Betis,38,17,10,11,50,50,0,61,NaN
7,NaN,7,Villarreal,38,15,13,10,60,44,16,58,NaN
8,NaN,8,Celta Vigo,38,14,11,13,55,57,−2,53,NaN
9,NaN,9,Granada,38,13,7,18,47,65,−18,46,NaN
10,NaN,10,Athletic Bilbao,38,11,13,14,46,42,4,46,NaN
11,NaN,11,Osasuna,38,11,11,16,37,48,−11,44,NaN
12,NaN,12,Cádiz,38,11,11,16,36,58,−22,44,NaN
13,NaN,13,Valencia,38,10,13,15,50,53,−3,43,NaN
14,NaN,14,Levante,38,9,14,15,46,57,−11,41,NaN

In [13]:
for index, row in dataExcel.iterrows():
    firstCell = row[0]
    #here we do row by row, and when there is a season row we store the season name and skip that header row
    if isinstance(firstCell, str) and firstCell.startswith("Season"):
        currentSeason = firstCell.replace("Season ", "")
        continue

    if pd.notna(row[1]) and pd.notna(row[2]):
        cleanRows.append({
            "Season": currentSeason,
            "Position" : row[1],
            "Team" : row[2],
            "Played" : row[3],
            "Wins" : row[4],
            "Draws" : row[5],
            "Losses" : row[6],
            "GoalsFor" : row[7],
            "GoalsAgainst" : row[8],
            "GoalDifference" : row[9],
            "Points": row[10]
        })

In [14]:
len(cleanRows)

100

In [17]:
fullData = pd.DataFrame(cleanRows)

fullData.head()

,Season,Position,Team,Played,Wins,Draws,Losses,GoalsFor,GoalsAgainst,GoalDifference,Points
0,2020-21,1,Atlético Madrid,38,26,8,4,67,25,42,86
1,2020-21,2,Real Madrid,38,25,9,4,67,28,39,84
2,2020-21,3,Barcelona,38,24,7,7,85,38,47,79
3,2020-21,4,Sevilla,38,24,5,9,53,33,20,77
4,2020-21,5,Real Sociedad,38,17,11,10,59,38,21,62

In [18]:
fullData.tail()

,Season,Position,Team,Played,Wins,Draws,Losses,GoalsFor,GoalsAgainst,GoalDifference,Points
95,2024-25,16,Girona,38,11,8,19,44,60,−16,41
96,2024-25,17,Sevilla,38,10,11,17,42,55,−13,41
97,2024-25,18,Leganés,38,9,13,16,39,56,−17,40
98,2024-25,19,Las Palmas,38,8,8,22,40,61,−21,32
99,2024-25,20,Valladolid,38,4,4,30,26,90,−64,16

In [19]:
fullData.columns

Index(['Season', 'Position', 'Team', 'Played', 'Wins', 'Draws', 'Losses',
       'GoalsFor', 'GoalsAgainst', 'GoalDifference', 'Points'],
      dtype='object')

In [22]:
fullData["Team"] = (fullData["Team"].astype(str).str.strip())

fullData["GoalDifference"] = (fullData["GoalDifference"].astype(str).str.replace("−","-",regex=False))

fullData[["Team","GoalDifference"]].head(10)

              Team GoalDifference
0  Atlético Madrid             42
1      Real Madrid             39
2        Barcelona             47
3          Sevilla             20
4    Real Sociedad             21
5       Real Betis              0
6       Villarreal             16
7       Celta Vigo             -2
8          Granada            -18
9  Athletic Bilbao              4

In [24]:
numberColumns = [
    "Position", "Played", "Wins", "Draws", "Losses", "GoalsFor", "GoalsAgainst", "GoalDifference", "Points"
]

for col in numberColumns:
    fullData[col] = pd.to_numeric(fullData[col], errors="coerce")

fullData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Season          100 non-null    object
 1   Position        100 non-null    int64
 2   Team            100 non-null    object
 3   Played          100 non-null    int64
 4   Wins            100 non-null    int64
 5   Draws           100 non-null    int64
 6   Losses          100 non-null    int64
 7   GoalsFor        100 non-null    int64
 8   GoalsAgainst    100 non-null    int64
 9   GoalDifference  100 non-null    int64
 10  Points          100 non-null    int64
dtypes: int64(9), object(2)
memory usage: 8.7+ KB

In [ ]:
seasonOrder = {
    "2020-21": 1,
    "2021-22": 2,
    "2022-23": 3,
    "2023-24": 4,
    "2024-25": 5
}

fullData["SeasonOrder"] = fullData["Season"].map(seasonOrder)

fullData[["Season","SeasonOrder"]]

     Season  SeasonOrder
0   2020-21            1
1   2020-21            1
2   2020-21            1
3   2020-21            1
4   2020-21            1
..      ...          ...
95  2024-25            5
96  2024-25            5
97  2024-25            5
98  2024-25            5
99  2024-25            5

[100 rows x 2 columns]

In [27]:
fullData[["Season","SeasonOrder"]].drop_duplicates

<bound method DataFrame.drop_duplicates of      Season  SeasonOrder
0   2020-21            1
1   2020-21            1
2   2020-21            1
3   2020-21            1
4   2020-21            1
..      ...          ...
95  2024-25            5
96  2024-25            5
97  2024-25            5
98  2024-25            5
99  2024-25            5

[100 rows x 2 columns]>

In [29]:
kpiSummary = fullData.groupby("Team").agg(
    SeasonsPlayed=("Season","count"),
    AveragePosition=("Position","mean"),
    AveragePoints=("Points","mean"),
    TotalWins=("Wins","sum"),
    TotalLosses=("Losses","sum"),
    TotalGoalsFor=("GoalsFor","sum"),
    TotalGoalsAgainst=("GoalsAgainst","sum"),
    AverageGoalDifference=("GoalDifference","mean")
).reset_index()

kpiSummary = kpiSummary.sort_values(by="AveragePoints",ascending=False)

kpiSummary.head(10)

,Team,SeasonsPlayed,AveragePosition,AveragePoints,TotalWins,TotalLosses,TotalGoalsFor,TotalGoalsAgainst,AverageGoalDifference
21,Real Madrid,5,1.600000,85.4,130,23,387,159,45.600000
4,Barcelona,5,1.800000,82.6,127,31,404,179,45.000000
3,Atlético Madrid,5,2.800000,77.2,116,36,340,174,33.200000
26,Villarreal,5,6.400000,60.8,84,54,318,237,16.200000
20,Real Betis,5,6.000000,60.6,83,53,263,226,7.400000
22,Real Sociedad,5,6.400000,60.2,84,57,236,195,8.200000
2,Athletic Bilbao,5,7.000000,58.0,77,54,251,187,12.800000
11,Girona,3,9.666667,57.0,49,41,187,161,8.666667
23,Sevilla,5,10.200000,55.6,75,62,243,226,3.400000
18,Osasuna,5,9.600000,48.2,62,73,204,249,-9.000000

In [30]:
fullData = fullData.sort_values(by=["Team","SeasonOrder"])

fullData[fullData["Team"] == "Eibar"]

,Season,Position,Team,Played,Wins,Draws,Losses,GoalsFor,GoalsAgainst,GoalDifference,Points,SeasonOrder
19,2020-21,20,Eibar,38,6,12,20,29,52,-23,30,1

In [32]:
fullData["PreviousSeasonOrder"] = fullData.groupby("Team")["SeasonOrder"].shift(1)
fullData["PreviousPosition"] = fullData.groupby("Team")["Position"].shift(1)
fullData["PreviousPoints"] = fullData.groupby("Team")["Points"].shift(1)

fullData[["Team","Season","Position","PreviousPosition","Points","PreviousPoints"]].head(20)

,Team,Season,Position,PreviousPosition,Points,PreviousPoints
15,Alavés,2020-21,16,NaN,38,NaN
39,Alavés,2021-22,20,16.0,31,38.0
69,Alavés,2023-24,10,20.0,46,31.0
94,Alavés,2024-25,15,10.0,42,46.0
56,Almería,2022-23,17,NaN,41,NaN
78,Almería,2023-24,19,17.0,21,41.0
9,Athletic Bilbao,2020-21,10,NaN,46,NaN
27,Athletic Bilbao,2021-22,8,10.0,55,46.0
47,Athletic Bilbao,2022-23,8,8.0,51,55.0
64,Athletic Bilbao,2023-24,5,8.0,68,51.0
83,Athletic Bilbao,2024-25,4,5.0,70,68.0
0,Atlético Madrid,2020-21,1,NaN,86,NaN
22,Atlético Madrid,2021-22,3,1.0,71,86.0
42,Atlético Madrid,2022-23,3,3.0,77,71.0
63,Atlético Madrid,2023-24,4,3.0,76,77.0
82,Atlético Madrid,2024-25,3,4.0,76,76.0
2,Barcelona,2020-21,3,NaN,79,NaN
21,Barcelona,2021-22,2,3.0,73,79.0
40,Barcelona,2022-23,1,2.0,88,73.0
61,Barcelona,2023-24,2,1.0,85,88.0

In [33]:
fullData["SeasonGap"] = fullData["SeasonOrder"] - fullData["PreviousSeasonOrder"]

fullData[fullData["SeasonGap"] > 1][["Team","Season","PreviousSeasonOrder","SeasonOrder","SeasonGap"]]

          Team   Season  PreviousSeasonOrder  SeasonOrder  SeasonGap
69      Alavés  2023-24                  2.0            4        2.0
93    Espanyol  2024-25                  3.0            5        2.0
79     Granada  2023-24                  2.0            4        2.0
57  Valladolid  2022-23                  1.0            3        2.0
99  Valladolid  2024-25                  3.0            5        2.0

In [34]:
fullData["PositionDrop"] = 0
fullData["PointDropPercentage"] = 0

continuousSeason = fullData["SeasonGap"] == 1

fullData.loc[continuousSeason, "PositionDrop"] = (
    fullData["Position"] - fullData["PreviousPosition"]
)

fullData.loc[continuousSeason, "PointDropPercentage"] = (
    (fullData["PreviousPoints"] - fullData["Points"]) / (fullData["PreviousPoints"] )
) * 100

/var/folders/lt/1bcjxg0s7mgfk5r2fwjnngr40000gn/T/ipykernel_36352/4011309800.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 18.42105263   8.69565217  48.7804878  -19.56521739   7.27272727
 -33.33333333  -2.94117647  17.44186047  -8.45070423   1.2987013
   0.           7.59493671 -20.54794521   3.40909091  -3.52941176
  13.20754717   6.52173913   4.65116279 -34.14634146  11.36363636
  -7.69230769  21.42857143 -16.66666667  40.47619048  11.9047619
  -2.63157895  -7.69230769  -2.38095238   2.3255814  -65.30612245
  49.38271605  17.39130435  20.          14.63414634 -28.20512821
  20.         -20.          -6.81818182 -12.76595745  15.09433962
 -15.55555556 -16.66666667  22.44897959 -36.84210526  -6.55737705
   7.69230769   5.          -5.26315789  -2.38095238   9.30232558
 -21.79487179  11.57894737   0.         -14.51612903  15.49295775
  23.33333333   9.09090909  30.          16.32653061   0.
 -11.62790698  12.5        -16.66666667   6.12244898  -1.72413793
  -8.47457627  17.1875     -32.0754717 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  fullData.loc[continuousSeason, "PointDropPercentage"] = (

In [35]:
fullData[[
    "Team","Season","Position","PreviousPosition","PositionDrop","Points","PreviousPoints","PointDropPercentage"
]].head(25)

,Team,Season,Position,PreviousPosition,PositionDrop,Points,PreviousPoints,PointDropPercentage
15,Alavés,2020-21,16,NaN,0,38,NaN,0.000000
39,Alavés,2021-22,20,16.0,4,31,38.0,18.421053
69,Alavés,2023-24,10,20.0,0,46,31.0,0.000000
94,Alavés,2024-25,15,10.0,5,42,46.0,8.695652
56,Almería,2022-23,17,NaN,0,41,NaN,0.000000
78,Almería,2023-24,19,17.0,2,21,41.0,48.780488
9,Athletic Bilbao,2020-21,10,NaN,0,46,NaN,0.000000
27,Athletic Bilbao,2021-22,8,10.0,-2,55,46.0,-19.565217
47,Athletic Bilbao,2022-23,8,8.0,0,51,55.0,7.272727
64,Athletic Bilbao,2023-24,5,8.0,-3,68,51.0,-33.333333
83,Athletic Bilbao,2024-25,4,5.0,-1,70,68.0,-2.941176
0,Atlético Madrid,2020-21,1,NaN,0,86,NaN,0.000000
22,Atlético Madrid,2021-22,3,1.0,2,71,86.0,17.441860
42,Atlético Madrid,2022-23,3,3.0,0,77,71.0,-8.450704
63,Atlético Madrid,2023-24,4,3.0,1,76,77.0,1.298701
82,Atlético Madrid,2024-25,3,4.0,-1,76,76.0,0.000000
2,Barcelona,2020-21,3,NaN,0,79,NaN,0.000000
21,Barcelona,2021-22,2,3.0,-1,73,79.0,7.594937
40,Barcelona,2022-23,1,2.0,-1,88,73.0,-20.547945
61,Barcelona,2023-24,2,1.0,1,85,88.0,3.409091
80,Barcelona,2024-25,1,2.0,-1,88,85.0,-3.529412
7,Celta Vigo,2020-21,8,NaN,0,53,NaN,0.000000
30,Celta Vigo,2021-22,11,8.0,3,46,53.0,13.207547
52,Celta Vigo,2022-23,13,11.0,2,43,46.0,6.521739
72,Celta Vigo,2023-24,13,13.0,0,41,43.0,4.651163

In [36]:
alertsList = fullData[
    (fullData["PositionDrop"] >= 4)
    | (fullData["PointDropPercentage"] >= 20)
    | ((fullData["Position"] > 15) & (fullData["Position"] <= 17) )
    | (fullData["Position"] >= 18)
    | (fullData["GoalDifference"] < 0)
].copy()

alertsList.head()

,Season,Position,Team,Played,Wins,Draws,Losses,GoalsFor,GoalsAgainst,GoalDifference,Points,SeasonOrder,PreviousSeasonOrder,PreviousPosition,PreviousPoints,SeasonGap,PositionDrop,PointDropPercentage
15,2020-21,16,Alavés,38,9,11,18,36,57,-21,38,1,NaN,NaN,NaN,NaN,0,0.000000
39,2021-22,20,Alavés,38,8,7,23,31,65,-34,31,2,1.0,16.0,38.0,1.0,4,18.421053
69,2023-24,10,Alavés,38,12,10,16,36,46,-10,46,4,2.0,20.0,31.0,2.0,0,0.000000
94,2024-25,15,Alavés,38,10,12,16,38,48,-10,42,5,4.0,10.0,46.0,1.0,5,8.695652
56,2022-23,17,Almería,38,11,8,19,49,65,-16,41,3,NaN,NaN,NaN,NaN,0,0.000000

In [37]:
alertsList["RiskReason"] = ""

alertsList.loc[alertsList["PositionDrop"] >= 4, "RiskReason"] += "Major position drop; "
alertsList.loc[alertsList["PointDropPercentage"] >= 20, "RiskReason"] += "Points dropped over 20%;"
alertsList.loc[(alertsList["Position"] > 15) & (alertsList["Position"] <= 17), "RiskReason"] += "Nearing relegation zone; "
alertsList.loc[alertsList["Position"] >= 18, "RiskReason"] += "Relegation zone; "
alertsList.loc[alertsList["GoalDifference"] < 0, "RiskReason"] += "Negative goal difference; "

alertsList[["Season","Team","Position","GoalDifference","RiskReason"]].head(20)

,Season,Team,Position,GoalDifference,RiskReason
15,2020-21,Alavés,16,-21,Nearing relegation zone; Negative goal differe...
39,2021-22,Alavés,20,-34,Major position drop; Relegation zone; Negative...
69,2023-24,Alavés,10,-10,Negative goal difference;
94,2024-25,Alavés,15,-10,Major position drop; Negative goal difference;
56,2022-23,Almería,17,-16,Nearing relegation zone; Negative goal differe...
78,2023-24,Almería,19,-32,Points dropped over 20%;Relegation zone; Negat...
7,2020-21,Celta Vigo,8,-2,Negative goal difference;
52,2022-23,Celta Vigo,13,-10,Negative goal difference;
72,2023-24,Celta Vigo,13,-11,Negative goal difference;
11,2020-21,Cádiz,12,-22,Negative goal difference;
36,2021-22,Cádiz,17,-16,Major position drop; Nearing relegation zone; ...
53,2022-23,Cádiz,14,-23,Negative goal difference;
77,2023-24,Cádiz,18,-29,Major position drop; Points dropped over 20%;R...
19,2020-21,Eibar,20,-23,Relegation zone; Negative goal difference;
16,2020-21,Elche,17,-21,Nearing relegation zone; Negative goal differe...
32,2021-22,Elche,13,-12,Negative goal difference;
59,2022-23,Elche,20,-37,Major position drop; Points dropped over 20%;R...
33,2021-22,Espanyol,14,-13,Negative goal difference;
58,2022-23,Espanyol,19,-17,Major position drop; Relegation zone; Negative...
93,2024-25,Espanyol,14,-11,Negative goal difference;

In [38]:
topTeams = kpiSummary.head(10)

kpiSummary

,Team,SeasonsPlayed,AveragePosition,AveragePoints,TotalWins,TotalLosses,TotalGoalsFor,TotalGoalsAgainst,AverageGoalDifference
21,Real Madrid,5,1.600000,85.400000,130,23,387,159,45.600000
4,Barcelona,5,1.800000,82.600000,127,31,404,179,45.000000
3,Atlético Madrid,5,2.800000,77.200000,116,36,340,174,33.200000
26,Villarreal,5,6.400000,60.800000,84,54,318,237,16.200000
20,Real Betis,5,6.000000,60.600000,83,53,263,226,7.400000
22,Real Sociedad,5,6.400000,60.200000,84,57,236,195,8.200000
2,Athletic Bilbao,5,7.000000,58.000000,77,54,251,187,12.800000
11,Girona,3,9.666667,57.000000,49,41,187,161,8.666667
23,Sevilla,5,10.200000,55.600000,75,62,243,226,3.400000
18,Osasuna,5,9.600000,48.200000,62,73,204,249,-9.000000
5,Celta Vigo,5,10.400000,47.600000,63,78,246,267,-4.200000
24,Valencia,5,11.800000,45.600000,56,74,224,250,-5.200000
19,Rayo Vallecano,4,12.000000,45.250000,45,61,154,196,-10.500000
17,Mallorca,4,12.500000,44.250000,45,65,141,194,-13.250000
10,Getafe,5,14.000000,40.800000,48,82,171,222,-10.200000
9,Espanyol,3,15.666667,40.333333,29,51,132,173,-13.666667
15,Leganés,1,18.000000,40.000000,9,16,39,56,-17.000000
6,Cádiz,4,15.250000,39.500000,35,64,127,217,-22.500000
0,Alavés,4,15.250000,39.250000,39,73,141,216,-18.750000
16,Levante,2,16.500000,38.000000,17,34,97,133,-18.000000
14,Las Palmas,2,17.500000,36.000000,18,40,73,108,-17.500000
12,Granada,3,15.666667,35.000000,25,59,129,205,-25.333333
8,Elche,3,16.666667,34.333333,24,59,104,174,-23.333333
13,Huesca,1,18.000000,34.000000,7,18,34,53,-19.000000
1,Almería,2,18.000000,31.000000,14,42,92,140,-24.000000
7,Eibar,1,20.000000,30.000000,6,20,29,52,-23.000000
25,Valladolid,3,19.000000,29.000000,20,67,93,210,-39.000000

In [41]:
riskByTeam = alertsList.groupby("Team").size().reset_index(name="NumberOfAlerts")
riskByTeam = riskByTeam.sort_values(by="NumberOfAlerts",ascending=False)

riskByTeam

              Team  NumberOfAlerts
19        Valencia               5
15         Osasuna               5
7           Getafe               5
0           Alavés               4
3            Cádiz               4
16  Rayo Vallecano               4
14        Mallorca               4
9          Granada               3
18         Sevilla               3
20      Valladolid               3
6         Espanyol               3
5            Elche               3
2       Celta Vigo               3
1          Almería               2
11      Las Palmas               2
13         Levante               2
12         Leganés               1
8           Girona               1
17   Real Sociedad               1
4            Eibar               1
10          Huesca               1

In [42]:
riskBySeason = alertsList.groupby("Season").size().reset_index(name="TotalAlerts")

riskBySeason

    Season  TotalAlerts
0  2020-21           12
1  2021-22           11
2  2022-23           12
3  2023-24           12
4  2024-25           13

In [43]:
outputPath = Path("reports/LaLiga_KPI_KRI_Reports.xlsx")

with pd.ExcelWriter(outputPath, engine="openpyxl") as writer:
    fullData.to_excel(writer, sheet_name="CleanData", index=False)
    kpiSummary.to_excel(writer,sheet_name="KPISummary", index=False)
    alertsList.to_excel(writer, sheet_name="KRIAlerts", index=False)
    topTeams.to_excel(writer, sheet_name="TopTeams", index=False)
    riskByTeam.to_excel(writer, sheet_name="RiskByTeam", index=False)
    riskBySeason.to_excel(writer, sheet_name="RiskBySeason", index=False)

outputPath

PosixPath('reports/LaLiga_KPI_KRI_Reports.xlsx')